# Generated by Django 5.1.3 on 2024-11-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("Percentage", "Percentage"), ("Amount", "Amount")],
                        max_length=20,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("expiration_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("usage_limit", models.PositiveIntegerField(default=1)),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
