# Generated by Django 5.1.3 on 2024-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expiration_date",
            field=models.DateTimeField(),
        ),
    ]
